ruyisdk/support-matrix

- LicheeCluster4A/README.md
- LicheeCluster4A/RevyOS/README.md
- LicheeCluster4A/RevyOS/README_Sipeed.md
- LicheeCluster4A/RevyOS/README_lpi4a.md
- LicheeCluster4A/openEuler/README.md
- LicheeCluster4A/openKylin/README.md
- README.md
- Tang_Mega_138K/FreeRTOS/README.md
- Tang_Mega_138K/README.md
- Tang_Mega_138K/RT-Thread/README.md
- Tang_Mega_138K/Zephyr/README.md
Add: TANG Mega 138K Pro (AE350)
Fix: Cluster 4A
> Cluster 4A & Sipeed TANG Mega 138K Pro (AE350)

- Duo/README.md
- Duo/ThreadX/README.md
- Duo/ThreadX/闪烁.md
- VisionFive2/Armbian/README.md
Also, move all videos (mp4 files) to GitHub assets.
> Add Duo/ThreadX

- Duo_S/Debian/README.md
- Duo_S/Debian/README_zh.md
- Jupiter/Bianbu/README.md
- Jupiter/Bianbu/README_zh.md
- Jupiter/README.md
- Jupiter/README_zh.md
- LicheePi4A/ArchLinux/README.md
- LicheePi4A/ArchLinux/README_zh.md
- LicheePi4A/Armbian/README.md
- LicheePi4A/Armbian/README_zh.md
- LicheePi4A/Fedora/README.md
- LicheePi4A/Fedora/README_chainsx.md
- LicheePi4A/Fedora/README_chainsx_zh.md
- LicheePi4A/Fedora/README_zh.md
- LicheePi4A/OpenWRT/README.md
- LicheePi4A/OpenWRT/README_zh.md
- LicheePi4A/README.md
- LicheePi4A/README_zh.md
- LicheePi4A/openEuler/README.md
- LicheePi4A/openEuler/README_zh.md
- LicheePi4A/openKylin/README.md
- LicheePi4A/openKylin/README_zh.md
- VisionFive2/README.md
- VisionFive2/README_zh.md
Duo S: update Debian to v1.4.0
Jupiter: add bianbu
lpi4a&visionfive2: fix typo
> DuoS, Jupiter, and others

- BPI-F3/Armbian/README_noble.md
- BPI-F3/Armbian/README_zh_noble.md
- BPI-F3/README.md
- BPI-F3/README_zh.md
- PIC64GX/Ubuntu/README.md
- PIC64GX/Ubuntu/README_zh.md
BPI-F3: Update Armbian to "noble"
PIC64GX: Add Ubuntu 24.04.1 LTS
> Update BPI-F3 and PIC64GX

- VisionFive2/Alpine/README.md
- VisionFive2/Alpine/README_zh.md
- VisionFive2/README.md
- VisionFive2/README_zh.md
- VisionFive2/openKylin/README.md
- VisionFive2/openKylin/README_zh.md
- Openkylin: update report to openkylin 2.0
- alpine: add test report
> VisionFive2/Openkylin: update report to openkylin 2.0, VisionFive2/Alpine: add alpine test report 

- .github/workflows/table.yaml
Add Table Gen to Pages and Artifacts.
Pages Gen is now off.
> CI: Add Table Gen.

- BPI-F3/Bianbu/README.md
- BPI-F3/Bianbu/README_zh.md
- BPI-F3/README.md
- BPI-F3/README_zh.md
* BPI-F3/Bianbu: update system version and links
* BPI-F3/Bianbu: update v2.0 boot logs and replay links
* BPI-F3: update readme bianbu download links
> BPi-F3: Update Bianbu to v2.0

- assets/generate_svgimage.py
- assets/src/svg_gen/svg_gen.py
- fix tmpfile error on Windows
- visual improvement: N/A -> -
> Metadata: fix and tweaks

- BPI-F3/Fedora/README.md
- BPI-F3/Fedora/README_zh.md
- BPI-F3/README.md
- BPI-F3/Fedora: added Fedora test report
- BPI-F3: added fedora
> BPI-F3: Added Fedora test report

- D1_LicheeRV/Ubuntu/README.md
- D1_LicheeRV/Ubuntu/README_LTS.md
- Icicle/Ubuntu/README.md
- Icicle/Ubuntu/README_LTS.md
- Mars/Ubuntu/README.md
- Mars/Ubuntu/README_LTS.md
- NeZha-D1s/Ubuntu/README.md
- NeZha-D1s/Ubuntu/README_LTS.md
- Unmatched/Ubuntu/README.md
- Unmatched/Ubuntu/README_LTS.md
> Metadata: sync metadata and test report

- BPI-F3/OpenWrt/README.md
- BPI-F3/OpenWrt/README_zh.md
- BPI-F3/README.md
BPI-F3/Fedora: added OpenWrt test report
BPI-F3: added openwrt
> BPI-F3: Added OpenWrt test report

- Duo/README.md
- Duo/README_zh.md
- Duo/RT-Thread/README.md
- Duo/RT-Thread/README_RTSmart.md
- Duo/RT-Thread/README_RTSmart_zh.md
- Duo/RT-Thread/README_zh.md
- Duo256m/README.md
- Duo256m/README_zh.md
- Duo256m/RT-Thread/README.md
- Duo256m/RT-Thread/README_RTSmart.md
- Duo256m/RT-Thread/README_RTSmart_zh.md
- Duo256m/RT-Thread/README_zh.md
- Add RT-Thread Smart test report for Milk-V Duo 256M
- Add RT-Thread test report for Milk-V Duo
- Updated & enhanced existing reports
> duo/duo256m: Add/Update RT-Thread/RT-Smart

- Duo/Fedora/README.md
- Duo/Fedora/README_zh.md
- Duo/README.md
- Duo/README_zh.md
> duo/fedora: update to fedora 41

- Duo/others.yml
openwrt: https://github.com/ruyisdk/support-matrix/issues/101#issuecomment-2472372309
yocto: https://github.com/ruyisdk/support-matrix/issues/88#issuecomment-2460575120
> Duo: openwrt/yocto CFH

- Duo/README.md
- Duo/README_zh.md
- Duo/Yocto/README.md
- Duo/Yocto/README_zh.md
- Duo/others.yml
- Duo256m/README.md
- Duo256m/README_zh.md
- Duo256m/Yocto/README.md
- Duo256m/Yocto/README_zh.md
- Add Yocto test report for Milk-V Duo (Close https://github.com/ruyisdk/support-matrix/issues/88)
- Add Yocto test report for Milk-V Duo 256M
> duo/duo256m: Add Yocto

- Longan_Nano/FreeRTOS/README_zh.md
- Longan_Nano/README.md
- Longan_Nano/README_zh.md
- Longan_Nano/RT-Thread/README.md
- Longan_Nano/ThreadX/README.md
- Longan_Nano/ThreadX/README_zh.md
- Update FreeRTOS test report for Sipeed Longan Nano (CFT -> Basic)
- Update RT-Thread test report for Sipeed Longan Nano (CFT -> Basic)
- Add ThreadX test report for Sipeed Longan Nano
> longan_nano: add FreeRTOS/RT-Thread/ThreadX

- BPI-F3/Alpine/README.md
- BPI-F3/Alpine/README_zh.md
- BPI-F3/README.md
- BPI-F3/README_zh.md
Changes:
- Added Alpine folder under BPI-F3
- Added OpenWrt Fedora and Apline links to README_zh.md under BPI-F3
> Added AlpineLinux report for BPI-F3

- LicheeRV_Nano/Alpine/README.md
- LicheeRV_Nano/Alpine/README_zh.md
- LicheeRV_Nano/BuildRoot/README.md
- LicheeRV_Nano/BuildRoot/README_zh.md
- LicheeRV_Nano/Fedora/README.md
- LicheeRV_Nano/Fedora/README_zh.md
- LicheeRV_Nano/README.md
- LicheeRV_Nano/README_zh.md
- Add Alpine Linux test report for Sipeed LicheeRV Nano
- Update BuildRoot test report for Sipeed LicheeRV Nano
- Add Fedora test report for Sipeed LicheeRV Nano
> licheervnano: Add/Update Alpine/BuildRoot/Fedora

- Duo256m/ArchLinux/README_zh.md
- Duo256m/openEuler/README_zh.md
- M0sense/README.md
- M0sense/README_zh.md
- M0sense/RT-Thread/README.md
- M0sense/RT-Thread/README_zh.md
- M1s/README_zh.md
- Add RT-Thread test report for Sipeed M0sense
- Fix title typo in Duo256M/ArchLinux
> m0sense: Add RT-Thread

- VisionFive2/NixOS/README.md
- VisionFive2/NixOS/README_zh.md
- VisionFive2/README.md
- VisionFive2/README_zh.md
- Add NixOS test report for StarFive VisionFive2
- ~~(reports for Milk-V Duo/Duo256M/DuoS are under way)~~
> visionfive2: Add NixOS

- BPI-F3/Bianbu/README.md
- BPI-F3/Bianbu/README_zh.md
BPI-F3: bianbu update to 2.0.4 version minimal image
> BPI-F3: bianbu update to 2.0.4

- LicheePi4A/README.md
- LicheePi4A/README_zh.md
- LicheePi4A/RevyOS/README.md
- LicheePi4A/RevyOS/README_zh.md
fix LicheePi4A/README.md openkylin item
> LicheePi4A/RevyOS(main): update revyos 20241229

- .github/workflows/package-index-sync.yaml
- assets/renew_ruyi_index.py
- assets/src/matrix_parser/matrix_parser.py
- assets/src/ruyi_index_updator/index_handler.py
- assets/src/ruyi_index_updator/upload_plugin/lm4a_revy.py
- assets/src/ruyi_index_updator/upload_plugin_base.py
- assets/src/ruyi_index_updator/version_diff.py
Feat?
- **CI: Allow sys to be either upper or lower**
Add restrict = "mirror" in dist property
- **CI: Fix restrict mirror, Add force upload arg**
RevyOS changed its u-boot name, which throw an error.
- **Updator: Catch plugin error**
- **Updator: Handel RevyOS LPi4A u-boot name change after 20240720**
> Updator: Cache image error, add mirror restrict and update image name

- BPI-F3/Armbian/README_noble.md
- BPI-F3/Armbian/README_noble_zh.md
- BPI-F3/README.md
BPI-F3: Armbian update to 25.2.0
> BPI-F3: Armbian update to 25.2.0

- .github/workflows/package-index-sync.yaml
- BPI-F3/openKylin/README.md
- Pioneer/openKylin/README.md
- assets/renew_ruyi_index.py
- assets/src/matrix_parser/matrix_parser.py
- assets/src/matrix_parser/version.py
- assets/src/ruyi_index_updator/config.py
- assets/src/ruyi_index_updator/ruyi_index_parser/parse_board_img.py
- assets/src/ruyi_index_updator/schema/pkg_manifest.py
- assets/src/ruyi_index_updator/upload_plugin/mirrorsite_getter.py
- assets/src/ruyi_index_updator/upload_plugin/th1520_revy.py
- assets/src/ruyi_index_updator/upload_plugin_base.py
- assets/src/ruyi_index_updator/version_diff.py
- **Fix: exclude u-boot from boot**
- **Refactor: Use ruyi's minifest defination**
- **Updator: Add update info**
- **Updator: Add plugin for bpi-f3 ok and pioneer ok**
> Updator: Add plugin for bpi-f3 ok and pioneer ok

- .github/workflows/package-index-sync.yaml
- assets/renew_ruyi_index.py
- assets/src/matrix_parser/matrix_parser.py
- assets/src/matrix_parser/version.py
- assets/src/ruyi_index_updator/config.py
- assets/src/ruyi_index_updator/ruyi_index_parser/parse_board_img.py
- assets/src/ruyi_index_updator/schema/pkg_manifest.py
- assets/src/ruyi_index_updator/upload_plugin/th1520_revy.py
- assets/src/ruyi_index_updator/upload_plugin_base.py
- assets/src/ruyi_index_updator/version_diff.py
- **Fix: exclude u-boot from boot**
- **Refactor: Use ruyi's minifest defination**
> Refactor: Use ruyi's minifest defination

- README.md
- README_zh.md
- assets/generate_svgimage.py
- assets/metadata.yml
- assets/src/matrix_parser/matrix_parser.py
> feat/tools: split customized linux distributions

- DongshanPI-STU/README.md
- DongshanPI-STU/README_zh.md
- DongshanPI-STU/TinaLinux/README.md
- DongshanPI-STU/TinaLinux/README_zh.md
- DongshanPI-STU/postmarketOS/README.md
- DongshanPI-STU/postmarketOS/README_zh.md
- mangopi_mq_pro/FreeBSD/README.md
- mangopi_mq_pro/FreeBSD/README_zh.md
- mangopi_mq_pro/NixOS/README.md
- mangopi_mq_pro/NixOS/README_zh.md
- mangopi_mq_pro/README.md
- mangopi_mq_pro/README_zh.md
- postmarketOS @ DongShanPI Nezha-STU
- Tina-Linux @ DongShanPI Nezha-STU
- FreeBSD @ MangoPi MQ-Pro
- NixOS @ MangoPi MQ-Pro
> Update mangopi_mq_pro and dongshanpi_stu

- Duo_S/README.md
- Duo_S/README_zh.md
- Duo_S/Ubuntu/README.md
- Duo_S/Ubuntu/README_zh.md
> Add Ubuntu testing reports for MilkV DuoS

- Duo_S/OpenWrt/README.md
- Duo_S/OpenWrt/README_zh.md
- Duo_S/README.md
- Duo_S/README_zh.md
- Duo_S/Ubuntu/README.md
- Add new report
- Also fix missing header for the Ubuntu report
> DuoS: Add OpenWrt test report

- assets/generate_svgimage.py
- assets/src/matrix_parser/matrix_parser.py
> ci: fix CFI

- assets/metadata.yml
> sort metadata,move buildroot and yocto to customized linux

- assets/src/matrix_parser/matrix_parser.py
> Fix: make key also case-insensitive

- LicheePi4A/Armbian/README.md
- LicheePi4A/Armbian/README_zh.md
- LicheePi4A/README.md
- LicheePi4A/README_zh.md
> LicheePi4A/Armbian: fix typo

- BPI-F3/openHarmony/README.md
> BPI-F3/openHarmony: Fix date

- Duo/OpenWrt/README.md
- Duo/OpenWrt/README_zh.md
- Duo/README.md
- Duo/README_zh.md
> Duo/OpenWrt: new test report

- Duo/others.yml
> Duo/OpenWrt: remove others.yml

- STAR64/Armbian/README.md
- STAR64/Armbian/README_zh.md
> Star64/Armbian: update link

- Duo256m/Debian/README.md
- Duo256m/Debian/README_zh.md
- Duo256m/README.md
- Duo256m/README_zh.md
- LicheeRV_Nano/Debian/README.md
- LicheeRV_Nano/Debian/README_zh.md
- LicheeRV_Nano/Fedora/README.md
- LicheeRV_Nano/Fedora/README_zh.md
- LicheeRV_Nano/README.md
- LicheeRV_Nano/README_zh.md
- Update Debian @ Duo 256M
- Update Debian @ LicheeRV Nano
- Update note regarding `dnf` for Fedora @ LicheeRV Nano (#215)
Closes #82.
> duo256/licheervnano: Update Debian/Fedora

- VisionFive2/Guix/README.md
- VisionFive2/Guix/README_zh.md
- VisionFive2/README.md
- VisionFive2/README_zh.md
> VisionFive2: Add Guix System test reports.

- Unmatched/Debian/README.md
- Unmatched/Debian/README_zh.md
> Unmatched: update Debian to trixie/sid

- Premier_P550/Debian/README.md
- Premier_P550/Debian/README_zh.md
- Premier_P550/README.md
- Premier_P550/README_zh.md
- Premier_P550/Ubuntu/README_LTS_zh.md
- Premier_P550/Ubuntu/REAMDE_LTS.md
- Premier_P550/Yocto/README_zh.md
- Premier_P550/Yocto/REAMDE.md
> Add a new board HiFive Premier P550 and it's Ubuntu, Yocto and Debian test reports (CFT).

- LicheeRV_Dock/openEuler/README.md
- LicheeRV_Dock/openEuler/README_zh.md
- NeZha/openEuler/README.md
- NeZha/openEuler/README_zh.md
- Unmatched/openEuler/README.md
- Unmatched/openEuler/README_zh.md
- VisionFive2/openEuler/README.md
- VisionFive2/openEuler/README_zh.md
> oERV: add notes

- LicheePi4A/README.md
- LicheePi4A_8_32/README.md
- VisionFive2/Guix/README.md
- VisionFive2/Guix/README_zh.md
- VisionFive2/README.md
- VisionFive2/README_zh.md
- Add Guix @ VisionFive2 (Behold the GNUisance!)
- Fix titles of two LicheePi 4A folders to reflect the variants
> visionfive2: Add Guix

- Premier_P550/Debian/README.md
- Premier_P550/README.md
- Premier_P550/Ubuntu/REAMDE_LTS.md
- Premier_P550/Yocto/REAMDE.md
> HiFive Premier P550: fix date and board matadata

- Mars/Guix/README.md
- Mars/Guix/README_zh.md
- Mars/README.md
- Mars/README_zh.md
- Mars/Ubuntu/README.md
- Mars/Ubuntu/README_zh.md
- assets/metadata.yml
> Add Guix and Ubuntu test reports for Mars. Add Guix to metadata.

- Unmatched/Armbian/README.md
- assets/metadata.yml
> Unmatched: fix frontmatter

- Unmatched/Armbian/README.md
- Unmatched/Armbian/README_zh.md
> Unmatched: update Armbian

- .github/workflows/pr.yml
- CONTRIBUTING.md
- CONTRIBUTING_zh.md
part of https://github.com/ruyisdk/ruyisdk/issues/27
> Enforce and document DCO compliance

- Duo_S/BuildRoot/README.md
- Duo_S/BuildRoot/README_v2.md
- Duo_S/BuildRoot/README_v2_zh.md
- Duo_S/BuildRoot/README_zh.md
- Duo_S/Debian/README.md
- Duo_S/Debian/README_zh.md
- Duo_S/NixOS/README.md
- Duo_S/NixOS/README_zh.md
- Duo_S/README.md
- Duo_S/README_zh.md
- assets/metadata.yml
- Update Debian @ Milk-V Duo S
- Update BuildRoot @ Milk-V Duo S (split into V1/V2)
- Add NixOS @ Milk-V Duo S
- Add Guix entry in `assets/metadata.yml`
> duos: Add/Update Debian/BuildRoot/NixOS

- NeZha-D1s/README.md
- NeZha-D1s/README_zh.md
- NeZha-D1s/Ubuntu/README.md
- NeZha-D1s/Ubuntu/README_zh.md
> NeZha-D1s/Ubuntu: Bump to Ubuntu 25.04 LTS

- STAR64/README.md
- STAR64/README_zh.md
- STAR64/Ubuntu/README.md
- STAR64/Ubuntu/README_zh.md
- STAR64/others.yml
> Star64/Ubuntu: Add Ubuntu 25.04

- Icicle/README.md
- Icicle/README_zh.md
- Icicle/Ubuntu/README.md
- Icicle/Ubuntu/README_zh.md
> Icicle/Ubuntu: Bump to Ubuntu 25.04

- PIC64GX/README.md
- PIC64GX/README_zh.md
- PIC64GX/Ubuntu/README.md
- PIC64GX/Ubuntu/README_zh.md
> PIC64GX/Ubuntu: Bump to Ubuntu 25.04

- Mars/README.md
- Mars/README_zh.md
- Mars/Ubuntu/README.md
- Mars/Ubuntu/README_zh.md
> Update Ubuntu test reports to 25.04 for Mars.

- Megrez/RockOS/README.md
- Megrez/RockOS/README_zh.md
> Megrez/RockOS: Bump to 20250423

- STAR64/Ubuntu/README_zh.md
> Star64/Ubuntu: fix typo

- Mars/ArchLinux/README.md
- Mars/ArchLinux/README_zh.md
- Mars/README.md
- Mars/README_zh.md
> Add ArchLinux test reports for Mars.

- Mars/Alpine/README.md
- Mars/Alpine/README_zh.md
- Mars/Fedora/README.md
- Mars/README.md
- Mars/README_zh.md
> Add Alpine test report for Mars and fix typos.

- NeZha/README.md
- NeZha/README_zh.md
- NeZha/Ubuntu/README_LTS.md
- NeZha/Ubuntu/README_LTS_zh.md
> Update Ubuntu 24.04.02 test report for Nezha.

- ESP32C2/FreeRTOS/README.md
- ESP32C2/FreeRTOS/README_zh.md
- ESP32C2/Zephyr/README.md
- ESP32C2/Zephyr/README_zh.md
- ESP32C6/FreeRTOS/README.md
- ESP32C6/FreeRTOS/README_zh.md
- ESP32C6/README.md
- ESP32C6/README_zh.md
- ESP32C6/Zephyr/README.md
- ESP32C6/Zephyr/README_zh.md
- ESP32H2/FreeRTOS/README.md
- ESP32H2/FreeRTOS/README_zh.md
- ESP32H2/README.md
- ESP32H2/README_zh.md
> Update: ESP32C2, ESP32H2, ESP32C6 test reports

- HengShanPi/README.md
- HengShanPi/README_zh.md
- HengShanPi/RT-Threand/README.md
- HengShanPi/RT-Threand/README_zh.md
> Add new Board HengShanPi and it's RT-Thread test report.

- LicheeRV_Dock/README.md
- LicheeRV_Dock/README_zh.md
- LicheeRV_Dock/Ubuntu/README.md
- LicheeRV_Dock/Ubuntu/README_zh.md
> LicheeRV_Dock: update ubuntu to 25.04

- LicheePi4A_8_32/NixOS/README.md
- LicheePi4A_8_32/NixOS/README_zh.md
- LicheePi4A_8_32/README.md
- LicheePi4A_8_32/README_zh.md
- LicheePi4A_8_32/Slackware/README.md
- LicheePi4A_8_32/Slackware/README_zh.md
> LiP4A_8_32: Add NixOS and Slackware

- ESP32C3/README.md
- ESP32C6/FreeRTOS/README_zh.md
- ESP32C6/README.md
- ESP32P4/FreeRTOS/README.md
- ESP32P4/FreeRTOS/README_zh.md
- ESP32P4/README.md
- ESP32P4/README_zh.md
> Update ESP32P4 test report and fix metadata errors

- VisionFive/Alpine/README.md
- VisionFive/Alpine/README_zh.md
- VisionFive/README.md
- VisionFive/README_zh.md
Signed-off-by: Ling Wang <lingwang@wcysite.com>
```sh
```
> Visionfive/Alpine: Update result to basic.

- Duo_S/Debian/README.md
- Duo_S/Debian/README_zh.md
- Duo_S/README.md
- Duo_S/README_zh.md
> DuoS: Dump Debian to v1.6.31

- LicheePi4A/README.md
- LicheePi4A/README_zh.md
- LicheePi4A/RevyOS/README.md
- LicheePi4A/RevyOS/README_zh.md
> LPi4A/RevyOS: Bump to 20250526

- Duo_S/BuildRoot/README_v2.md
- Duo_S/BuildRoot/README_v2_zh.md
> Duo S: Dump BuildRoot

- Duo_S/Debian/README.md
- Duo_S/Debian/README_zh.md
- Duo_S/README.md
- Duo_S/README_zh.md
> DuoS: Dump Debian

- Megrez/Deepin/README.md
- Megrez/Deepin/README_zh.md
- Premier_P550/Deepin/README.md
- Premier_P550/Deepin/README_zh.md
> fix dead link for deepin

- OrangePi-RV2/Debian/README.md
- OrangePi-RV2/Debian/README_zh.md
> OrangePi RV2: Add Debian Trixie test report (basic).

- LicheePi4A/RevyOS/README.md
> docs: Correct sys_ver in LicheePi4A RevyOS README
